version: "3"

services:
  prison-api:
    image: wiremock/wiremock:latest
    container_name: prison-api
    ports:
      - "8091:8081"
    volumes:
      - $PWD/wiremock-docker:/home/wiremock
    command: --verbose --global-response-templating --port=8081

  prisoner-search-api:
    image: wiremock/wiremock:latest
    container_name: prisoner-search-api
    ports:
      - "8092:8081"
    volumes:
      - $PWD/wiremock-docker:/home/wiremock
    command: --verbose --global-response-templating --port=8081

  oauth-server:
    image: wiremock/wiremock:latest
    container_name: oauth-server
    ports:
      - "8090:8081"
    volumes:
      - $PWD/wiremock-docker:/home/wiremock
    command: --verbose --global-response-templating --port=8081

networks:
  hmpps:
